### ISSUE TITLE
transcript polish 

### ISSUE THREAD

**Issue by nicielpl** [crashtheparty/EnchantmentSolution#79] opened 2020-04-25 13:12 UTC
**Describe the bug**
Today I started to translate plugins from the beginning works normally but when I translated the whole thing with a smith with a few loopholes it dumped everything into English
**Debug.yml**
https://pastebin.com/Y7SUqKyq

**To Reproduce**
.https://pastebin.com/r9L9RrdY

serever versions is 1.15.2

**Comment by crashtheparty** [comment] 2020-05-04 00:50
That is not what steps to reproduce should look like, but because it took a week to look into, I'll ignore that part for now.

1. Setting "language" to "pl_pl" in config.yml will do nothing because pl_pl is not a supported language currently. If you would like to send in a full translation into Polish, please wait until 2.3 releases, and then send over a full language file.
2. The first bug in the config (NullPointer at SnapshotInventory.checkItem()) will be fixed later today or tomorrow in the next update. 
3. The second bug (Trouble adding width_plus_plus enchantment) comes from using /reload, which EnchantmentSolution does not support.

**Comment by nicielpl** [comment] 2020-05-04 05:20
ok so finish the crack and send them here? because I practically finished it even now I can take care of it

**Comment by crashtheparty** [comment] 2020-05-10 03:10
Has this been fixed?

**Closed as completed** 2020-06-03 22:58 UTC
Labels: bug, question
